export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO_TODO";
export const TOGGLE_DISPLAY_ORDER = "TOGGLE_DISPLAY_ORDER";
export const MOVE_COMPLETED_TODO = "MOVE_COMPLETED_TODO";
export const CHANGE_VISIBILITY_FILTER = "CHANGE_VISIBILITY_FILTER";